spin_manifest_version = 2

[application]
description = "A hello world application that serves content from a C++ program and a Rust program"
name = "spin-wagi-hello"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"
executor = { type = "wagi" } # _start (the default entrypoint) is automatically mapped to main()

[[trigger.http]]
route = "/goodbye"
component = "goodbye"
executor = { type = "http" }

[component.hello]
source = "hello-cpp/hello.wasm"

[component.hello.build]
command = "make build -C hello-cpp"

[component.goodbye]
source = "goodbye-rust/target/wasm32-wasi/release/goodbye.wasm"

[component.goodbye.build]
command = "cargo build --target wasm32-wasi --release --manifest-path goodbye-rust/Cargo.toml"

