spin_manifest_version = 2

[application]
description = "A hello world application that serves content from a C++ program and a Rust program"
name = "spin-wagi-hello"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"
executor = { type = "wagi" } # _start (the default entrypoint) is automatically mapped to main()

[[trigger.http]]
route = "/goodbye"
component = "goodbye"
executor = { type = "http" }

[component.hello]
source = "wagi-http-cpp/main.wasm"
[component.hello.build]
command = "make build -C wagi-http-cpp"

[component.goodbye]
source = "http-rust/target/wasm32-wasi/release/goodbyerust.wasm"
[component.goodbye.build]
command = "cargo build --target wasm32-wasi --release --manifest-path http-rust/Cargo.toml"
